/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Ability;
import soundManagement.SoundPlayer;

/**
 *
 * @author F776
 */
public class AbilityTable extends javax.swing.JFrame implements Serializable {

    private final ArrayList<Ability> abilityList = MainWindow.getInstance().getAbilityArray();
    private boolean isTableFilled = false;

    /**
     * Creates new form AbilityTable
     */
    public AbilityTable() {
        initComponents();
        if (!isTableFilled) {
            fillAbilityTbl();
            isTableFilled = true;
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAbility = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abilities Pokedex");
        setIconImage(MainWindow.getPokeballImage().getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tblAbility.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAbility.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAbility);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        SoundPlayer.menuClosed();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAbility;
    // End of variables declaration//GEN-END:variables

    private void fillAbilityTbl() {
        DefaultTableModel tbl = (DefaultTableModel) this.tblAbility.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbl);
        this.tblAbility.setRowSorter(sorter);
        tbl.setRowCount(0);

        for (Ability a : this.abilityList) {
            tbl.addRow(new Object[]{
                a.getId(), a.getName(), a.getDescription()
            });

        }
    }
}
