/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.TreeSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Item;
import soundManagement.SoundPlayer;

/**
 *
 * @author F776
 */
public class ItemsTable extends javax.swing.JFrame  implements Serializable{

    private final ArrayList<Item> itemList = MainWindow.getInstance().getItemArray();
    private boolean isTableFilled = false;

    /**
     * Creates new form ItemsTable
     */
    public ItemsTable() {
        initComponents();

        if (!isTableFilled) {
            fillItemTbl();
            isTableFilled = true;
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item Pokedex");
        setIconImage(MainWindow.getPokeballImage().getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItems.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblItems);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        SoundPlayer.menuClosed();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItems;
    // End of variables declaration//GEN-END:variables

    private void fillItemTbl() {
        DefaultTableModel tbl = (DefaultTableModel) this.tblItems.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(tbl);
        this.tblItems.setRowSorter(sorter);
        tbl.setRowCount(0);

        for (Item i : this.itemList) {
            tbl.addRow(new Object[]{
                i.getId(), i.getName(), i.getDescription()
            });
        }
    }

}
