/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Interface.IDefaultAttributes;
import java.io.Serializable;
import soundManagement.SoundPlayer;

/**
 *
 * @author nicoo
 */
public class PokedexClose extends javax.swing.JFrame implements IDefaultAttributes, Serializable {

    /**
     * Creates new form PokedexClose
     */
    public PokedexClose() {
        initComponents();
        this.instanceMainWindow = MainWindow.getInstance();
        this.setIconImage(GREAT_TUSK_ICON.getImage());
        btnOpenDex.setOpaque(false);
        btnOpenDex.setContentAreaFilled(false);
        btnOpenDex.setBorderPainted(false);
        this.setLocationRelativeTo(null);

    }

    private static PokedexClose instance;
    public static PokemonTable pokemonTable = PokemonTable.getInstance();

    public static PokedexClose getInstance() {
        if (instance == null) {
            instance = new PokedexClose();
        }
        return instance;
    }

    private void initializePokemonTable() {
        if (pokemonTable == null) {
            pokemonTable = new PokemonTable();
            System.out.println("Pokémon Table loaded");
        }
    }

    private MainWindow instanceMainWindow;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnOpenDex = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokémon Generator");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenDex.setBorderPainted(false);
        btnOpenDex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpenDex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpenDexMouseEntered(evt);
            }
        });
        btnOpenDex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDexActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpenDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 60));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pokedex/closedDexMainResized.png"))); // NOI18N
        lblBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackgroundMouseEntered(evt);
            }
        });
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenDexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDexActionPerformed
        // TODO add your handling code here:
        instanceMainWindow.setVisible(true);
        SoundPlayer.programOpened();
        SoundPlayer.playBackgroundTheme();
        this.dispose();
    }//GEN-LAST:event_btnOpenDexActionPerformed

    private void lblBackgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMouseEntered
        // TODO add your handling code here:
//        initializePokemonTable();
    }//GEN-LAST:event_lblBackgroundMouseEntered

    private void btnOpenDexMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenDexMouseEntered
        // TODO add your handling code here:
//        initializePokemonTable();
    }//GEN-LAST:event_btnOpenDexMouseEntered

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        SoundPlayer.optionSelected();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenDex;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBackground;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

//        try {
//            
//                    javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
//                
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            PokedexClose.getInstance().setVisible(true);
        });
    }
}
